### ISSUE TITLE
feat: wrapping async concepts

### ISSUE THREAD

**Issue by dijonkitchen** [samedhi/firemore#8]
Seems kind of complicated for people to know and utilize `go` blocks, channels, and async concepts. Perhaps your wrapper over the Firestore API can encapsulate that? 

Examples:
https://github.com/samedhi/firemore/blame/master/README.md#L91
https://github.com/samedhi/firemore/blame/master/README.md#L123
https://github.com/samedhi/firemore/blame/master/README.md#L143
https://github.com/samedhi/firemore/blob/master/README.md#build-local-state-atom

**Comment by samedhi** [comment]
Fundamentally, this is an asynchronous concept. You are talking about writing something to a cloud database that pulls a lot of tricks to make things "feel" like they are local. 

I do have high hopes for sort of hiding the `core.async` stuff when you use the yet-to-be-written re-frame interface to this. Imagine an event that looks similar to how re-frame does xmlhttprequest. This would allow the client to "hide" the async. #37
