### ISSUE TITLE
Order of query statements

### ISSUE THREAD

**Issue by dijonkitchen** [samedhi/firemore#9]
Based on the Firestore data model, should the API utilize a map? It looks like the Javascript version gets properties from the collection, then document, then data. I can't tell if you can really re-order the map's keys like a declarative SQL statement and still have it be translated properly for Firestore. 

https://github.com/samedhi/firemore/blame/master/README.md#L226-L236

**Comment by samedhi** [comment]
I am not sure I see what you mean, if you are talking about :where, :order, :limit then those are applied in a particular order regardless of what (order, there is no real order) you specify in the map.
